apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: openlxpxse-data02
  name: openlxpxse-data02
  namespace: elasticsearch ##TO-DO: update this to dynamically update with variable from Terraform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
